### PR TITLE
Fixing #7 by coping the extension names

### LINKED ISSUE #7: Fail to create vulkan device
In NVK.cpp.
```cpp
device_extension_names.resize(physical_devices.size());
for(int j=0; j<physical_devices.size(); j++)
{
    // ...
    std::vector<VkExtensionProperties> device_extensions;
    device_extensions.resize(count);
    result = vkEnumerateDeviceExtensionProperties(physical_devices[j], NULL, &count, &device_extensions[0]);
    device_extension_names[j].resize(device_extensions.size() );
    for(int i=0; i<device_extensions.size(); i++)
    {
        LOGI("%d: HW Device Extension: %s\n", i,device_extensions[i].extensionName);
        device_extension_names[j][i] = device_extensions[i].extensionName;
    }
}
```
`device_extension_names` will be invalid when `device_extensions` leave for loop.
Then fail to create device.

### PR DESCRIPTION
**Pull request by AntonioNoack**
This pull request fixes #7.

I had the same issue on my RTX 3070, and got the crash messages, because the char* was freed before use.
```
ERROR: [Loader Message] Code 0 : loader_validate_device_extensions: Device extension  not supported by selected physical device or enabled layers.
ERROR: [Loader Message] Code 0 : vkCreateDevice: Failed to validate extensions in list
```

My solution copies the data, that would be freed after, into new strings.

### CODE REVIEW

File: NVK.cpp [hunk 1]
```diff
@@ -1151,7 +1151,12 @@ bool NVK::utInitialize(WindowSurface* pWindowSurface)
         for(int i=0; i<device_extensions.size(); i++)
         {
             LOGI("%d: HW Device Extension: %s\n", i,device_extensions[i].extensionName);
-            device_extension_names[j][i] = device_extensions[i].extensionName;
+            // When device_extensions leaves the scope, VkExtensionProperties will free extensionName, so we need to copy it.
+            // We cannot free this data within this method, because that causes a crash after vkCreateDevice.
+            int len = strlen(device_extensions[i].extensionName) + 1; // +1 for \0
+            char* copiedName = new char[len];
+            std::memcpy(copiedName, device_extensions[i].extensionName, len);
+            device_extension_names[j][i] = copiedName;
```
Comment (silasvorne) [inline NVK.cpp]: Memory leak occurs.
Maybe define `device_extension_names` as
```cpp
std::vector<std::vector<std::string>> device_extension_names;
```
could be simpler.

Comment (AntonioNoack) [reply NVK.cpp]: I fixed the leak 😊.
Unfortunately, devInfo.ppEnabledExtensionNames is a char**, so we still need an array/vector of pointers (line 1193-1195).

In my previous test I got an error when using std::vector<char*>, because I assumed std::vector(length) sets the capacity to length, and the size to 0, but it sets both capacity and size to length 😅. This caused the first elements to be null, because I was using push_back().

Comment (silasvorne) [reply NVK.cpp]: Yes, it is upset that `char**` is not compatible with `std::vector<std::string>`.

**Comment by silasvorne** [comment]
Seems like code owner has not accepted any PR yet :(

**Comment by NBickford-NV** [comment]
This merge request looks good to me - thank you! I'll merge this in shortly.
